[build]
  publish = "."
  command = "echo 'Building site...'"

[build.environment]
  REACT_APP_Maps_API_KEY = "$Maps_API_KEY"
  REACT_APP_MIDTRANS_CLIENT_KEY = "$MIDTRANS_CLIENT_KEY"
  REACT_APP_FIREBASE_API_KEY = "$FIREBASE_API_KEY"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "$FIREBASE_AUTH_DOMAIN"
  REACT_APP_FIREBASE_PROJECT_ID = "$FIREBASE_PROJECT_ID"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "$FIREBASE_STORAGE_BUCKET"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "$FIREBASE_MESSAGING_SENDER_ID"
  REACT_APP_FIREBASE_APP_ID = "$FIREBASE_APP_ID"
  REACT_APP_FIREBASE_DATABASE_URL = "$FIREBASE_DATABASE_URL"
